// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

#ifndef _MYST_CLOCK_H
#define _MYST_CLOCK_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#define NANO_IN_SECOND 1000000000

#define MICRO_IN_SECOND 1000000

typedef struct clock_ctrl {
  long realtime0;
  long monotime0;
  long now;
  unsigned long interval;
  int done;
} clock_ctrl;

int myst_setup_clock(struct clock_ctrl *ctrl);

#endif /* _MYST_CLOCK_H */
